---
title: "Leaderboard"
date: "`r Sys.time()`"
github_document:
    toc_dept: 1
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```


```{r preprocess, include = FALSE}
require(knitr)
require(data.table)
require(DataChallenge.2017)

evs			<- dc.evaluate(save=TRUE)
baseline	<- subset(evs, FILE=='/Users/Oliver/git/DataChallenge.2017/data_private/DataChallenge_olli0601_baseline_predictions.csv')[, MSE]
evs			<- subset(evs, FILE!='/Users/Oliver/git/DataChallenge.2017/data_private/DataChallenge_olli0601_baseline_predictions.csv')
evs			<- evs[order(MSE), ]
evs[, RANK:= seq_len(nrow(evs))]
evs[, ABOVE_BASELINE:= as.character(factor(MSE<=baseline, levels=c(TRUE,FALSE), labels=c('yes','no')))]
evs[, FILE:=NULL]

set(evs, evs[, which(grepl('_16:',TIME, fixed=TRUE))], 'TIME', '2017-11-20_15:58:28')

dtop10		<- subset(evs, RANK<=10, select=c(TEAM_ID, SUBMISSION_ID, TIME, MSE, RANK, ABOVE_BASELINE))
dbestofteam	<- evs[, {
			z<- which.min(MSE)
			list(SUBMISSION_ID=SUBMISSION_ID[z], TIME=TIME[z], MSE=MSE[z], RANK=RANK[z], ABOVE_BASELINE=ABOVE_BASELINE[z])
		}, by='TEAM_ID']
```    

### 2017 Winners 
<br>

The **WINNERS** of the 2017 Data Challenge of the MSc in Statistics are 

**TEAM BOOM BOOM (FRANCK LIN, LAN YU, JUNYU GAO)**.

<br>

**Second prize**: **team Birdo (Wenrui Zheng, Richard Burn, Edoardo
Lisi)**. 

**Third prize**: **team Koopa (Ting Au, Efstratios Xenelis,
Catarina Alves)**.

<br>

Congratulations to all.

<br>

### Current top 10 submissions

```{r top10, results = 'asis', echo=FALSE}
kable(dtop10)
```

### Top submissions by team  

```{r bestofteam, results = 'asis', echo=FALSE}
kable(dbestofteam)
```